apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    volumeMounts:
    - name: init
      mountPath: /docker-entrypoint-initdb.d
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: myshoes
    ports:
    - containerPort: 3306
  volumes:
  - name: init
    hostPath:
      path: /initdb.d
      type: Directory
