name: Create Cluster

on: workflow_dispatch

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
      - name: Create annotation for build error
        run: kubectl get pods
      - name: Create annotation for build error
        run: bash ./setup.sh
