name: Create Cluster

on: workflow_dispatch

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create annotation for build error
        run: cd initdb.d && curl -o schema.sql https://raw.githubusercontent.com/whywaita/myshoes/master/pkg/datastore/mysql/schema.sql
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          config: ./kind-config.yaml
      - name: Create annotation for build error
        run: kubectl get pods
      - name: Make executeable
        run: chmod +x ./setup.sh
      - name: Setup cluster
        run: ./setup.sh
      - name: Test request
        run: curl localhost:30000/target
