name: "Install latest LXD"
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

    - name: Setup LXD
      uses: canonical/setup-lxd@0.1.1
      with:
        channel: latest/stable  # switch from distro's LTS channel to latest/stable

    - name: Launch container
      run: |
        lxc launch ubuntu:22.04 u1
